services:
  prefect:
    image: prefecthq/prefect:3-latest
    container_name: prefect
    restart: unless-stopped
    environment:
      PREFECT_LOGGING_LEVEL: INFO
    ports:
      - "4200:4200"
    command: >
      bash -lc "
      prefect server start --host 0.0.0.0 --port 4200
      "
    healthcheck:
      # string form => CMD-SHELL; the entire heredoc is ONE string
      test: |
        python - <<'PY'
        import urllib.request, sys, socket
        socket.setdefaulttimeout(2)
        try:
            urllib.request.urlopen('http://localhost:4200/api', timeout=2)
            sys.exit(0)
        except Exception:
            sys.exit(1)
        PY
      interval: 5s
      timeout: 3s
      retries: 60
      start_period: 20s

  prefect-worker:
    image: saferoads/prefect-docker-worker:latest
    container_name: prefect-worker
    restart: unless-stopped
    depends_on:
      prefect:
        condition: service_healthy
    environment:
      PREFECT_LOGGING_LEVEL: INFO
      PREFECT_API_URL: http://prefect:4200/api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes: {}
