services:
  prefect:
    image: prefecthq/prefect:3-latest
    container_name: prefect
    restart: unless-stopped
    environment:
      PREFECT_LOGGING_LEVEL: INFO
    ports:
      - "4200:4200"
    command: >
      prefect server start --host 0.0.0.0 --port 4200
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4200/api >/dev/null"]
      interval: 5s
      timeout: 3s
      retries: 40

  prefect-worker:
    image: prefecthq/prefect:3-latest
    container_name: prefect-worker
    restart: unless-stopped
    environment:
      PREFECT_LOGGING_LEVEL: INFO
      PREFECT_API_URL: http://prefect:4200/api
      PIP_ROOT_USER_ACTION: ignore  
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SSLMODE: ${POSTGRES_SSLMODE}
      HUGGINGFACE_HUB_TOKEN: ${HUGGINGFACE_HUB_TOKEN}
      HF_MODEL_REPO: ${HF_MODEL_REPO}
      HF_MODEL_FILE: ${HF_MODEL_FILE}
    depends_on:
      - prefect
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -lc "
      pip install -q --no-cache-dir 'prefect-docker>=0.5.0' docker &&
      # wait for the API (extra safety even with healthcheck)
      until curl -sf http://prefect:4200/api >/dev/null; do
        echo 'Waiting for Prefect API...'; sleep 2; 
      done &&
      # create the pool only if missing
      (prefect work-pool inspect docker-safe-roads >/dev/null 2>&1) ||
        prefect work-pool create -t docker docker-safe-roads &&
      # start the docker worker
      prefect worker start --type docker --pool docker-safe-roads
      "

