services:
  prefect:
    image: prefecthq/prefect:3-latest
    container_name: prefect
    restart: unless-stopped
    environment:
      PREFECT_LOGGING_LEVEL: INFO
    ports:
      - "4200:4200"
    command: >
      bash -lc "
      prefect server start --host 0.0.0.0 --port 4200
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4200/api >/dev/null"]
      interval: 5s
      timeout: 3s
      retries: 40

  prefect-worker:
    build:
      context: .
      dockerfile: worker.dockerfile
    image: saferoads/prefect-docker-worker:latest
    container_name: prefect-worker
    restart: unless-stopped
    depends_on:
      prefect:
        condition: service_healthy
    environment:
      PREFECT_LOGGING_LEVEL: INFO
      PREFECT_API_URL: http://prefect:4200/api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# If you run Postgres in compose, add a service here (optional).
# Otherwise, ensure PGHOST points to a reachable hostname/IP on this host.

# Project volume (server state)
volumes:
  prefect_data: {}
