SAFE_ROADS_API: "https://AmanKhokhar-safe-roads-catboost.hf.space"
SAFE_ROADS_API_TOKEN: ""

INPUT_TABLE: "roads_features"
OUT_TABLE: "prediction"
BATCH_SIZE: 10000  
READ_CHUNKSIZE: 10000
WRITE_CHUNKSIZE: 10000
HTTP_TIMEOUT: 120
HTTP_RETRY: 3