name: Build & Push Docker Image to GHCR

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: "Extra image tag (e.g. v1.2.3). Leave blank to skip."
        required: false
        default: ""

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE: ghcr.io/aman-khokhar18/safe-roads   # hardcoded, all lowercase
      SHA_TAG: ${{ github.sha }}
      EXTRA_TAG: ${{ github.event.inputs.tag }}

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      # PRs: build only (no push)
      - name: Build (no push) for PRs
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Log in to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ env.SHA_TAG }}
            ${{ env.IMAGE }}:${{ github.event.inputs.tag && join(fromJSON('["' + toJSON(github.event.inputs.tag) + '"]'), '') || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show pushed image refs
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "Pushed:"
          echo " - ${IMAGE}:latest"
          echo " - ${IMAGE}:${SHA_TAG}"
          if [ -n "${EXTRA_TAG}" ]; then
            echo " - ${IMAGE}:${EXTRA_TAG}"
          fi
