name: Build & Push Docker Image to GHCR

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: "Optional extra image tag"
        required: false
        default: ""

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE: ghcr.io/aman-khokhar18/safe-roads
      SHA_TAG: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      # PRs: build only (no push)
      - name: Build (no push) for PRs
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Main / manual: login + push
      - name: Log in to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (latest + sha)
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ env.SHA_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Optional extra tag (only on manual runs when provided)
      - name: Push extra tag
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag != '' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE }}:${{ github.event.inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
